blank_issues_enabled: false
contact_links:
  - name: Documentation ğŸ“š
    url: https://docs.needlify.com/
    about: Learn how to use the website
  - name: Wiki ğŸ“
    url: https://github.com/Needlify/Needlify-v2/wiki
    about: Check out the official docs for answers to common questions and learn how to contribute
  - name: Questions & discussions ğŸ¤”
    url: https://github.com/Needlify/Needlify-v2/discussions
    about: Ask questions, request features & discuss
  - name: Community Discord ğŸ’¬
    url: https://discord.gg/aVYBcexpEE
    about: Community discussions, interactive support, contributor help
  - name: Twitter account ğŸ¦œ
    url: https://twitter.com/NeedlifyCom
    about: Official twitter account with the latest news
